server:
    port: 8080
    
spring:
    application:
        name: API_GATEWAY
        
    cloud:
        gateway:
            routes:
                - id: DOCTOR-SERVICE
                  uri: 
                    lb://DOCTOR-SERVICE
                  predicates:
                      - Path=/doctor/**
                      
                - id: ADDRESS-SERVICE
                  uri: 
                    lb://ADDRESS-SERVICE
                  predicates:
                      - Path=/address/**
                      
                - id: FEED-SERVICE
                  uri: 
                    lb://FEED-SERVICE
                  predicates:
                      - Path=/feed/**
                            